project:
  type: website
  output-dir: docs

website:
  title: "MICHAEL ADU-GYAMFI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

