project:
  type: website
  output-dir: docs

website:
  title: "MICHAEL ADU-GYAMFI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    right:
      - href: contact.qmd
        text: Contact
    tools:
      - icon: twitter
        href: https://twitter.com/home 
      - icon: facebook
        href: https://www.facebook.com/ 
    page-footer:
      right: Built with [Quarto](https://quarto.org/)

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

